language: clojure
before_install:
  - sudo service postgresql stop
  - sudo apt-get update
  - sudo apt-get remove --purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo apt-get install postgresql-client-9.4 postgresql-9.4 postgresql-contrib-9.4

before_script:
  - pg_lsclusters
  - sudo su postgres -c "echo 'host all all 127.0.0.1/32 md5' > /etc/postgresql/9.4/main/pg_hba.conf"
  - cp example-config.json test/config.json
  - psql -c 'create database fhirterm;' -U postgres
  - psql -c "create role fhirterm with superuser login encrypted password 'fhirterm';" -U postgres
  - wget -O data/loinc.zip https://www.dropbox.com/s/u4qsfc7ciiaqfqa/LOINC_248_Text.zip?dl=1
  - wget -O data/snomed.zip https://www.dropbox.com/s/rr5bho3npfnviji/SnomedCT_Release_INT_20140731_only_data.zip?dl=1

script:
  - lein test :tasks
  - lein test :integration
