language: clojure

before_install:
  - sudo service postgresql stop
  - sudo apt-get update
  - sudo apt-get remove --purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo apt-get install postgresql-client-9.4 postgresql-9.4 postgresql-contrib-9.4

before_script:
  - pg_lsclusters
  - sudo su postgres -c "echo 'host all all 127.0.0.1/32 md5' >> /etc/postgresql/9.4/main/pg_hba.conf"
  - sudo service postgresql reload
  - cp etc/example-config.json test/config.json
  - sudo su postgres -c "psql -c 'create database fhirterm;'"
  - sudo su postgres -c "psql -c 'create database fhirbase;'"
  - sudo su postgres -c "psql -c \"create role fhirterm with superuser login encrypted password 'fhirterm';\""
  - sudo su postgres -c "psql -c \"create role fhirbase with superuser login encrypted password 'fhirbase';\""
  - wget -O data/loinc.zip https://www.dropbox.com/s/u4qsfc7ciiaqfqa/LOINC_248_Text.zip?dl=1
  - wget -O data/snomed.zip https://www.dropbox.com/s/rr5bho3npfnviji/SnomedCT_Release_INT_20140731_only_data.zip?dl=1
  - wget -O /tmp/fhirbase.sql https://raw.githubusercontent.com/fhirbase/fhirbase/master/fhirbase--1.0.sql
  - PGPASSWORD=fhirbase psql -U fhirbase -h localhost fhirbase < /tmp/fhirbase.sql
  - wget -O /tmp/fhirplace-master.zip https://github.com/fhirbase/fhirplace/archive/master.zip
  - wget -O /tmp/routemap-master.zip https://github.com/niquola/route-map/archive/master.zip
  - cd .. && unzip /tmp/fhirplace-master.zip
  - unzip /tmp/routemap-master.zip -d fhirplace-master/lib && rm -rf fhirplace-master/lib/route-map && mv fhirplace-master/lib/route-map-master fhirplace-master/lib/route-map
  - cd fhirplace-master && lein run

script:
  - LOG_LEVEL=info lein test :tasks
  - lein test :integration
