language: clojure
before_install:
  - sudo apt-get update
  - sudo apt-get install postgresql-client postgresql-server postgresql-contrib

before_script:
  - df -h
  - pg_lsclusters
  - ls -lah /var/ramfs
  - sudo su postgres -c '/usr/lib/postgresql/9.3/bin/initdb -D /tmp/pg93'
  - cat /tmp/pg93/pg_hba.conf
  - sudo su postgres -c '/usr/lib/postgresql/9.3/bin/pg_ctl start -w -D /tmp/pg93'
  - cp example-config.json test/config.json
  - psql -c 'create database fhirterm;' -U postgres
  - psql -c "create role fhirterm with superuser login encrypted password 'fhirterm';" -U postgres
  - wget -O data/loinc.zip https://www.dropbox.com/s/u4qsfc7ciiaqfqa/LOINC_248_Text.zip?dl=1
  - wget -O data/snomed.zip https://www.dropbox.com/s/rr5bho3npfnviji/SnomedCT_Release_INT_20140731_only_data.zip?dl=1

script:
  - lein test :tasks
  - lein test :integration
